# Dataset config
dataset: "ocean"            # The name of the dataset
mode: "rgb"                 # Grayscale ("L") or true color ("RGB")

# Model config
channels: 3                 # Number of channels in each image. 1 for grayscale, 3 for true color
img_size: 256               # Size of each image dimension. Must be an exact power of 2

# Training config
n_epochs: 200               # Number of epochs of training
batch_size: 64              # Size of the batches
lr: 0.0002                  # Adam: learning rate
b1: 0.5                     # Adam: decay of first order momentum of gradient
b2: 0.999                   # Adam: decay of first order momentum of gradient
n_cpu: 8                    # Number of CPU threads to use during batch preparation
sample_interval: 400        # Interval between image sampling
